Add media key debugging option
vector-im/element-call pull request #2717
Opened 2024-11-04 14:56 UTC by toger5

2024-11-04 14:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/element-hq/element-call?pullRequest=2717) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/element-hq/element-call?pullRequest=2717) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/element-hq/element-call?pullRequest=2717) it.</sub>

2024-12-06 13:05 UTC, hughns requested changes
Please can the redundant changes that are in https://github.com/element-hq/element-call/pull/2771 be removed.

2025-05-20 09:16 UTC, toger5 commented
@BillCarsonFr This is superseeded by your key debugging tooling right?
If so feel free to close this!

2025-08-04 16:00 UTC, toger5 commented
Closing this since multiple aspects of this have changed and this might not be the most ideal way to this kind of debugging anymore. Its easier to start new again if necassary.

2025-08-04 16:00 UTC, closed without merging