docker compose non hostnetwork setup
vector-im/element-call pull request #2719
Opened 2024-11-04 23:41 UTC by fkwp

Purpose of this refactoring is to create a self containing development environment for Element Call using the localhost domain namespace:
- Minimum Synapse Setup (servername: synapse.localhost)
- LiveKit JWT Service (Note requires Federation API and hence a TLS reverse proxy)
- Minimum TLS reverse proxy (servername: synapse.localhost) Note certificates are valid for at least 10 years from now
- Minimum LiveKit SFU Setup using dev defaults for config
- Redis db for completness

2024-11-06 18:45 UTC, AndrewFerr commented on dev-backend-docker-compose.yml
> +      - ./backend/dev_livekit.yaml:/etc/livekit.yaml
For compatibility with SELinux-enabled hosts, put the `:Z` flag on each volume entry:
```suggestion
      - ./backend/dev_livekit.yaml:/etc/livekit.yaml:Z
```
(and all the others)

It should be safe to use this flag even on non-SELinux systems, as documentation says it gets ignored then: https://docs.docker.com/reference/compose-file/services/#short-syntax-5

2024-11-07 10:37 UTC, Half-Shot requested changes
I had a go with this and it worked wonderfully, just a couple of questions before approval.

2024-11-07 10:37 UTC, Half-Shot commented on README.md
> -To use it, add a SFU parameter in your local config `./public/config.json`:
We've lost the advice about copying the config over?

2024-11-07 10:37 UTC, Half-Shot commented on config/config.sample.json
> +      "base_url": "http://synapse.localhost:8008",
Is this change to the sample expected? Not just to the devenv.json?

2024-11-07 16:47 UTC, AndrewFerr requested changes

2024-11-07 16:47 UTC, AndrewFerr commented on dev-backend-docker-compose.yml
> +      - ./backend/redis.conf:/etc/redis.conf
```suggestion
      - ./backend/redis.conf:/etc/redis.conf:Z
```

2024-11-07 16:47 UTC, AndrewFerr commented on dev-backend-docker-compose.yml
> +      - ./backend/dev_homeserver.yaml:/data/cfg/homeserver.yaml
```suggestion
      - ./backend/synapse_tmp:/data:Z
      - ./backend/dev_homeserver.yaml:/data/cfg/homeserver.yaml:Z
```

2024-11-07 16:47 UTC, AndrewFerr commented on dev-backend-docker-compose.yml
> +      - ./backend/tls_localhost_cert.pem:/root/ssl/cert.pem
```suggestion
      - ./backend/tls_localhost_nginx.conf:/etc/nginx/conf.d/default.conf:Z
      - ./backend/tls_localhost_key.pem:/root/ssl/key.pem:Z
      - ./backend/tls_localhost_cert.pem:/root/ssl/cert.pem:Z
```

2024-11-07 18:47 UTC, AndrewFerr approved these changes

2024-11-07 20:42 UTC, Half-Shot approved these changes

2024-11-07 20:45 UTC, merged