changes Loading room... to Loading...
vector-im/element-call pull request #900
Opened 2023-02-08 08:56 UTC by abhijain2003

I have changed the Loading room... to Loading...
in GroupCallView and GroupCallLoader files to maintain consistency in loading component in web.

targeting issue 
https://github.com/vector-im/element-call/issues/461#issuecomment-1422197846
#461

2023-02-08 10:59 UTC, SimonBrandner requested changes
Thank you though you need to run the `yarn i18n` script now

2023-02-08 12:35 UTC, abhijain2003 commented
I did I think

2023-02-08 14:45 UTC, SimonBrandner commented
Did you commit the changes the script did?

2023-02-08 15:16 UTC, abhijain2003 commented
should I do it again

2023-02-09 07:26 UTC, SimonBrandner commented
Can you try again? It seems the script did no changes on your side, while on my side it does change `app.json` with your changes

2023-02-09 07:34 UTC, abhijain2003 commented
as you said, I just did it again. let me know now it is working or not

2023-02-09 07:56 UTC, SimonBrandner commented
Can you write down everything you did?

2023-02-09 07:57 UTC, abhijain2003 commented
I just run a command yarn i18n in the root directory.

2023-02-09 07:57 UTC, abhijain2003 commented
do you want me write what and where I have made changes as well?

2023-02-09 07:58 UTC, SimonBrandner commented
> do you want me write what and where I have made changes as well?

Yep, I still can't see what I should see... it would help me figure out what's going on

2023-02-09 08:00 UTC, abhijain2003 commented
![Screenshot 2023-02-09 133232](https://user-images.githubusercontent.com/91718608/217751921-ac327fd8-92af-45da-93a5-f7cfa5f91e5e.png)


the only thing I did was

2023-02-09 08:13 UTC, SimonBrandner commented
I meant what you did in the terminal, what commands you ran, what files changed, how you committed the changes etc.

2023-02-09 08:17 UTC, abhijain2003 commented
sorry for that, 

ok, so commands I run (after changes).
yarn i18n
git init
get remote add upstream <original repo link>
get fetch upstream 
git checkout -b abhijain2003/loginui
git add .
git commit -m "message"
git push origin my_branch

2023-02-09 08:32 UTC, SimonBrandner commented
No worries, can you try this and paste the terminal output:

```
git checkout abhijain2003/loadingui
git pull
yarn i18n
git add .
git commit - m "i18n"
```

2023-02-09 08:33 UTC, abhijain2003 commented
sure

2023-02-09 08:37 UTC, SimonBrandner commented
And also `git push` in the end :)

2023-02-09 08:39 UTC, abhijain2003 commented
when I am doing all these, there is no changes is happening, in code
![Screenshot 2023-02-09 141016](https://user-images.githubusercontent.com/91718608/217760100-205a3900-ea51-4080-9706-b5a830113d5c.png)

as you can see there is nothing to commit is coming

2023-02-10 08:55 UTC, abhijain2003 commented
do you have any update for this, is there any way I can help you

2023-02-13 04:16 UTC, robintown requested changes

2023-02-13 04:16 UTC, robintown commented on src/room/GroupCallLoader.tsx
> +        <h1>{t("Loading...")}</h1>
Please use the `…` Unicode character rather than 3 dots, for consistency with our other strings

2023-02-13 04:17 UTC, abhijain2003 commented
sure

2023-02-13 04:23 UTC, abhijain2003 commented
I have commited the requested changes,

2023-04-23 09:09 UTC, SimonBrandner commented
Hey, sorry for the delay here! This would be cool to merge but it's not clear to me what is going on here with the `i18n` script. Do you think you'll be able to figure it out or should I take over?

2023-04-23 15:49 UTC, abhijain2003 commented
I think I can, but these days I am busy with my freelance clients I would need some time, but for the community i think the best is you should take it over to someone else

highly apologies for this.

will surely contribute to the community in different way

2023-04-24 10:25 UTC, SimonBrandner commented
> highly apologies for this.

No worries at all :)

2023-05-10 13:36 UTC, merged